apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.gemforegroundservice'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.gemforegroundservice"
  defaultConfig {
    minSdkVersion getExpoDefaultMinSdkVersion(project)
    targetSdkVersion getExpoDefaultTargetSdkVersion(project)
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.13.1"
}
